---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.8
    driver:
      box: sbeliakou/centos-6.8-x86_64

suites:
  - name: default
    run_list:
      - recipe[web::default]
